import { PrismaClient, EventStatus, ContestType, ContestStatus } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding OctaFight Fantasy database...");

  // Create admin user
  const admin = await prisma.user.upsert({
    where: { email: "admin@octafight.gg" },
    update: {},
    create: {
      email: "admin@octafight.gg",
      username: "octafight_admin",
      displayName: "OctaFight Admin",
      role: "ADMIN",
      xp: 9999,
      level: 7,
      rank: "GOAT",
      balance: 10000,
    },
  });

  // Seed fighters
  const fightersData = [
    {
      name: "Jon Jones",
      nickname: "Bones",
      weightClass: "Heavyweight",
      record: "27-1-0",
      wins: 27, losses: 1, draws: 0,
      height: "6'4\"", weight: "248 lbs", reach: "84.5\"", stance: "Orthodox", age: 37,
      salary: 11500, projectedPoints: 82, avgFantasyPoints: 78,
      ownership: 38, knockoutPct: 48, submissionPct: 15, decisionPct: 37,
      strikeAccuracy: 57, strikeDefense: 64, takedownAccuracy: 44, takedownDefense: 95,
      significantStrikes: 4.3, takedownsPerFight: 1.9, ranking: 1,
    },
    {
      name: "Islam Makhachev",
      nickname: null,
      weightClass: "Lightweight",
      record: "26-1-0",
      wins: 26, losses: 1, draws: 0,
      height: "5'10\"", weight: "155 lbs", reach: "70\"", stance: "Orthodox", age: 33,
      salary: 11000, projectedPoints: 79, avgFantasyPoints: 75,
      ownership: 41, knockoutPct: 23, submissionPct: 46, decisionPct: 31,
      strikeAccuracy: 55, strikeDefense: 69, takedownAccuracy: 61, takedownDefense: 86,
      significantStrikes: 4.1, takedownsPerFight: 2.8, ranking: 1,
    },
    {
      name: "Alex Pereira",
      nickname: "Poatan",
      weightClass: "Light Heavyweight",
      record: "12-2-0",
      wins: 12, losses: 2, draws: 0,
      height: "6'4\"", weight: "205 lbs", reach: "79\"", stance: "Orthodox", age: 37,
      salary: 10500, projectedPoints: 85, avgFantasyPoints: 80,
      ownership: 45, knockoutPct: 83, submissionPct: 0, decisionPct: 17,
      strikeAccuracy: 51, strikeDefense: 58, takedownAccuracy: 15, takedownDefense: 72,
      significantStrikes: 5.2, takedownsPerFight: 0.2, ranking: 1,
    },
    {
      name: "Dricus du Plessis",
      nickname: "Stillknocks",
      weightClass: "Middleweight",
      record: "22-2-0",
      wins: 22, losses: 2, draws: 0,
      height: "6'1\"", weight: "185 lbs", reach: "76\"", stance: "Orthodox", age: 31,
      salary: 9500, projectedPoints: 71, avgFantasyPoints: 68,
      nationality: "South Africa", countryFlag: "🇿🇦",
      ownership: 33, knockoutPct: 68, submissionPct: 14, decisionPct: 18,
      strikeAccuracy: 52, strikeDefense: 57, takedownAccuracy: 38, takedownDefense: 74,
      significantStrikes: 4.8, takedownsPerFight: 1.1, ranking: 1,
    },
    {
      name: "Leon Edwards",
      nickname: "Rocky",
      weightClass: "Welterweight",
      record: "22-3-0",
      wins: 22, losses: 3, draws: 0,
      height: "6'0\"", weight: "170 lbs", reach: "74\"", stance: "Orthodox", age: 33,
      salary: 9000, projectedPoints: 68, avgFantasyPoints: 64,
      nationality: "UK", countryFlag: "🇬🇧",
      ownership: 29, knockoutPct: 41, submissionPct: 9, decisionPct: 50,
      strikeAccuracy: 50, strikeDefense: 62, takedownAccuracy: 35, takedownDefense: 75,
      significantStrikes: 4.4, takedownsPerFight: 0.8, ranking: 1,
    },
    {
      name: "Alexander Volkanovski",
      nickname: "The Great",
      weightClass: "Featherweight",
      record: "26-3-0",
      wins: 26, losses: 3, draws: 0,
      height: "5'6\"", weight: "145 lbs", reach: "71.5\"", stance: "Orthodox", age: 36,
      salary: 9500, projectedPoints: 73, avgFantasyPoints: 70,
      nationality: "Australia", countryFlag: "🇦🇺",
      ownership: 35, knockoutPct: 35, submissionPct: 4, decisionPct: 61,
      strikeAccuracy: 58, strikeDefense: 57, takedownAccuracy: 47, takedownDefense: 71,
      significantStrikes: 5.7, takedownsPerFight: 1.9, ranking: 2,
    },
    {
      name: "Sean O'Malley",
      nickname: "Sugar",
      weightClass: "Bantamweight",
      record: "18-1-0",
      wins: 18, losses: 1, draws: 0,
      height: "5'11\"", weight: "135 lbs", reach: "72\"", stance: "Orthodox", age: 30,
      salary: 9000, projectedPoints: 76, avgFantasyPoints: 72,
      ownership: 40, knockoutPct: 72, submissionPct: 6, decisionPct: 22,
      strikeAccuracy: 54, strikeDefense: 55, takedownAccuracy: 33, takedownDefense: 68,
      significantStrikes: 5.1, takedownsPerFight: 0.5, ranking: 1,
    },
    {
      name: "Alexandre Pantoja",
      nickname: "The Cannibal",
      weightClass: "Flyweight",
      record: "28-5-0",
      wins: 28, losses: 5, draws: 0,
      height: "5'5\"", weight: "125 lbs", reach: "67\"", stance: "Orthodox", age: 34,
      salary: 8500, projectedPoints: 67, avgFantasyPoints: 64,
      nationality: "Brazil", countryFlag: "🇧🇷",
      ownership: 28, knockoutPct: 29, submissionPct: 46, decisionPct: 25,
      strikeAccuracy: 47, strikeDefense: 55, takedownAccuracy: 42, takedownDefense: 68,
      significantStrikes: 3.8, takedownsPerFight: 1.6, ranking: 1,
    },
    {
      name: "Zhang Weili",
      nickname: "Magnum",
      weightClass: "Women's Strawweight",
      record: "24-3-0",
      wins: 24, losses: 3, draws: 0,
      height: "5'4\"", weight: "115 lbs", reach: "63\"", stance: "Orthodox", age: 35,
      salary: 8500, projectedPoints: 70, avgFantasyPoints: 66,
      nationality: "China", countryFlag: "🇨🇳",
      ownership: 36, knockoutPct: 50, submissionPct: 17, decisionPct: 33,
      strikeAccuracy: 56, strikeDefense: 60, takedownAccuracy: 44, takedownDefense: 63,
      significantStrikes: 5.3, takedownsPerFight: 1.4, ranking: 1,
    },
    {
      name: "Ilia Topuria",
      nickname: "El Matador",
      weightClass: "Featherweight",
      record: "16-0-0",
      wins: 16, losses: 0, draws: 0,
      height: "5'7\"", weight: "145 lbs", reach: "71\"", stance: "Orthodox", age: 27,
      salary: 10000, projectedPoints: 78, avgFantasyPoints: 74,
      nationality: "Georgia", countryFlag: "🇬🇪",
      ownership: 43, knockoutPct: 81, submissionPct: 6, decisionPct: 13,
      strikeAccuracy: 55, strikeDefense: 61, takedownAccuracy: 50, takedownDefense: 80,
      significantStrikes: 4.6, takedownsPerFight: 1.2, ranking: 1,
    },
    {
      name: "Tom Aspinall",
      nickname: null,
      weightClass: "Heavyweight",
      record: "15-3-0",
      wins: 15, losses: 3, draws: 0,
      height: "6'5\"", weight: "254 lbs", reach: "78\"", stance: "Orthodox", age: 31,
      salary: 9000, projectedPoints: 74, avgFantasyPoints: 70,
      nationality: "UK", countryFlag: "🇬🇧",
      ownership: 32, knockoutPct: 53, submissionPct: 33, decisionPct: 14,
      strikeAccuracy: 53, strikeDefense: 60, takedownAccuracy: 48, takedownDefense: 77,
      significantStrikes: 4.8, takedownsPerFight: 1.5, ranking: 2,
    },
    {
      name: "Khamzat Chimaev",
      nickname: "Borz",
      weightClass: "Welterweight",
      record: "14-0-0",
      wins: 14, losses: 0, draws: 0,
      height: "6'1\"", weight: "170 lbs", reach: "73\"", stance: "Orthodox", age: 30,
      salary: 9500, projectedPoints: 77, avgFantasyPoints: 73,
      nationality: "Sweden", countryFlag: "🇸🇪",
      ownership: 42, knockoutPct: 57, submissionPct: 29, decisionPct: 14,
      strikeAccuracy: 57, strikeDefense: 65, takedownAccuracy: 68, takedownDefense: 82,
      significantStrikes: 4.7, takedownsPerFight: 3.2, ranking: 3,
    },
    {
      name: "Justin Gaethje",
      nickname: "The Highlight",
      weightClass: "Lightweight",
      record: "25-5-0",
      wins: 25, losses: 5, draws: 0,
      height: "5'11\"", weight: "155 lbs", reach: "70\"", stance: "Orthodox", age: 36,
      salary: 8500, projectedPoints: 72, avgFantasyPoints: 68,
      ownership: 31, knockoutPct: 68, submissionPct: 4, decisionPct: 28,
      strikeAccuracy: 47, strikeDefense: 52, takedownAccuracy: 28, takedownDefense: 74,
      significantStrikes: 6.2, takedownsPerFight: 0.6, ranking: 2,
    },
    {
      name: "Charles Oliveira",
      nickname: "Do Bronx",
      weightClass: "Lightweight",
      record: "34-10-0",
      wins: 34, losses: 10, draws: 0,
      height: "5'10\"", weight: "155 lbs", reach: "74\"", stance: "Orthodox", age: 35,
      salary: 8000, projectedPoints: 69, avgFantasyPoints: 65,
      nationality: "Brazil", countryFlag: "🇧🇷",
      ownership: 27, knockoutPct: 41, submissionPct: 47, decisionPct: 12,
      strikeAccuracy: 46, strikeDefense: 54, takedownAccuracy: 55, takedownDefense: 70,
      significantStrikes: 4.0, takedownsPerFight: 1.9, ranking: 4,
    },
    {
      name: "Dustin Poirier",
      nickname: "The Diamond",
      weightClass: "Lightweight",
      record: "30-9-0",
      wins: 30, losses: 9, draws: 0,
      height: "5'9\"", weight: "155 lbs", reach: "72\"", stance: "Southpaw", age: 35,
      salary: 8000, projectedPoints: 67, avgFantasyPoints: 63,
      ownership: 25, knockoutPct: 53, submissionPct: 13, decisionPct: 34,
      strikeAccuracy: 48, strikeDefense: 57, takedownAccuracy: 36, takedownDefense: 63,
      significantStrikes: 5.0, takedownsPerFight: 0.7, ranking: 5,
    },
    {
      name: "Colby Covington",
      nickname: "Chaos",
      weightClass: "Welterweight",
      record: "17-4-0",
      wins: 17, losses: 4, draws: 0,
      height: "5'11\"", weight: "170 lbs", reach: "72\"", stance: "Orthodox", age: 36,
      salary: 7500, projectedPoints: 62, avgFantasyPoints: 58,
      ownership: 18, knockoutPct: 18, submissionPct: 6, decisionPct: 76,
      strikeAccuracy: 43, strikeDefense: 61, takedownAccuracy: 54, takedownDefense: 72,
      significantStrikes: 5.4, takedownsPerFight: 4.1, ranking: 3,
    },
    {
      name: "Robert Whittaker",
      nickname: "The Reaper",
      weightClass: "Middleweight",
      record: "25-7-0",
      wins: 25, losses: 7, draws: 0,
      height: "6'0\"", weight: "185 lbs", reach: "74.5\"", stance: "Orthodox", age: 34,
      salary: 8000, projectedPoints: 65, avgFantasyPoints: 62,
      nationality: "Australia", countryFlag: "🇦🇺",
      ownership: 22, knockoutPct: 44, submissionPct: 8, decisionPct: 48,
      strikeAccuracy: 52, strikeDefense: 61, takedownAccuracy: 36, takedownDefense: 73,
      significantStrikes: 5.0, takedownsPerFight: 0.8, ranking: 2,
    },
    {
      name: "Max Holloway",
      nickname: "Blessed",
      weightClass: "Featherweight",
      record: "25-7-0",
      wins: 25, losses: 7, draws: 0,
      height: "5'11\"", weight: "145 lbs", reach: "69\"", stance: "Orthodox", age: 33,
      salary: 8500, projectedPoints: 70, avgFantasyPoints: 67,
      nationality: "USA", countryFlag: "🇺🇸",
      ownership: 30, knockoutPct: 36, submissionPct: 4, decisionPct: 60,
      strikeAccuracy: 55, strikeDefense: 56, takedownAccuracy: 42, takedownDefense: 64,
      significantStrikes: 7.3, takedownsPerFight: 0.6, ranking: 3,
    },
    {
      name: "Jiri Prochazka",
      nickname: "Denisa",
      weightClass: "Light Heavyweight",
      record: "30-4-1",
      wins: 30, losses: 4, draws: 1,
      height: "6'4\"", weight: "205 lbs", reach: "80\"", stance: "Southpaw", age: 32,
      salary: 8500, projectedPoints: 71, avgFantasyPoints: 67,
      nationality: "Czech Republic", countryFlag: "🇨🇿",
      ownership: 31, knockoutPct: 73, submissionPct: 7, decisionPct: 20,
      strikeAccuracy: 44, strikeDefense: 52, takedownAccuracy: 25, takedownDefense: 78,
      significantStrikes: 5.3, takedownsPerFight: 0.4, ranking: 2,
    },
    {
      name: "Sean Strickland",
      nickname: "Tarzan",
      weightClass: "Middleweight",
      record: "29-6-0",
      wins: 29, losses: 6, draws: 0,
      height: "6'0\"", weight: "185 lbs", reach: "76\"", stance: "Orthodox", age: 33,
      salary: 8000, projectedPoints: 62, avgFantasyPoints: 59,
      ownership: 20, knockoutPct: 20, submissionPct: 10, decisionPct: 70,
      strikeAccuracy: 48, strikeDefense: 63, takedownAccuracy: 33, takedownDefense: 72,
      significantStrikes: 5.2, takedownsPerFight: 0.5, ranking: 3,
    },
    {
      name: "Paulo Costa",
      nickname: "Borrachinha",
      weightClass: "Middleweight",
      record: "14-3-0",
      wins: 14, losses: 3, draws: 0,
      height: "6'1\"", weight: "185 lbs", reach: "72\"", stance: "Orthodox", age: 33,
      salary: 7000, projectedPoints: 60, avgFantasyPoints: 57,
      nationality: "Brazil", countryFlag: "🇧🇷",
      ownership: 17, knockoutPct: 71, submissionPct: 7, decisionPct: 22,
      strikeAccuracy: 55, strikeDefense: 49, takedownAccuracy: 20, takedownDefense: 69,
      significantStrikes: 5.8, takedownsPerFight: 0.5, ranking: 6,
    },
    {
      name: "Merab Dvalishvili",
      nickname: "The Machine",
      weightClass: "Bantamweight",
      record: "17-4-0",
      wins: 17, losses: 4, draws: 0,
      height: "5'7\"", weight: "135 lbs", reach: "67\"", stance: "Orthodox", age: 33,
      salary: 8000, projectedPoints: 65, avgFantasyPoints: 61,
      nationality: "Georgia", countryFlag: "🇬🇪",
      ownership: 26, knockoutPct: 6, submissionPct: 12, decisionPct: 82,
      strikeAccuracy: 45, strikeDefense: 66, takedownAccuracy: 72, takedownDefense: 71,
      significantStrikes: 4.2, takedownsPerFight: 5.1, ranking: 2,
    },
    {
      name: "Arman Tsarukyan",
      nickname: "Ahalkalakets",
      weightClass: "Lightweight",
      record: "22-3-0",
      wins: 22, losses: 3, draws: 0,
      height: "5'9\"", weight: "155 lbs", reach: "71\"", stance: "Southpaw", age: 28,
      salary: 8000, projectedPoints: 66, avgFantasyPoints: 62,
      nationality: "Armenia", countryFlag: "🇦🇲",
      ownership: 24, knockoutPct: 36, submissionPct: 27, decisionPct: 37,
      strikeAccuracy: 51, strikeDefense: 58, takedownAccuracy: 44, takedownDefense: 75,
      significantStrikes: 4.5, takedownsPerFight: 2.1, ranking: 3,
    },
    {
      name: "Belal Muhammad",
      nickname: "Remember The Name",
      weightClass: "Welterweight",
      record: "23-3-0",
      wins: 23, losses: 3, draws: 0,
      height: "5'11\"", weight: "170 lbs", reach: "74\"", stance: "Orthodox", age: 36,
      salary: 8500, projectedPoints: 64, avgFantasyPoints: 60,
      ownership: 21, knockoutPct: 17, submissionPct: 22, decisionPct: 61,
      strikeAccuracy: 46, strikeDefense: 65, takedownAccuracy: 52, takedownDefense: 75,
      significantStrikes: 3.9, takedownsPerFight: 2.5, ranking: 2,
    },
    {
      name: "Israel Adesanya",
      nickname: "The Last Stylebender",
      weightClass: "Middleweight",
      record: "24-4-0",
      wins: 24, losses: 4, draws: 0,
      height: "6'4\"", weight: "185 lbs", reach: "80\"", stance: "Southpaw", age: 35,
      salary: 8500, projectedPoints: 67, avgFantasyPoints: 63,
      nationality: "Nigeria", countryFlag: "🇳🇬",
      ownership: 28, knockoutPct: 54, submissionPct: 8, decisionPct: 38,
      strikeAccuracy: 52, strikeDefense: 63, takedownAccuracy: 28, takedownDefense: 78,
      significantStrikes: 4.6, takedownsPerFight: 0.3, ranking: 5,
    },
    {
      name: "Ciryl Gane",
      nickname: "Bon Gamin",
      weightClass: "Heavyweight",
      record: "12-2-0",
      wins: 12, losses: 2, draws: 0,
      height: "6'4\"", weight: "247 lbs", reach: "80\"", stance: "Orthodox", age: 34,
      salary: 8000, projectedPoints: 66, avgFantasyPoints: 62,
      nationality: "France", countryFlag: "🇫🇷",
      ownership: 23, knockoutPct: 42, submissionPct: 8, decisionPct: 50,
      strikeAccuracy: 50, strikeDefense: 60, takedownAccuracy: 40, takedownDefense: 74,
      significantStrikes: 4.1, takedownsPerFight: 0.9, ranking: 3,
    },
    {
      name: "Curtis Blaydes",
      nickname: "Razor",
      weightClass: "Heavyweight",
      record: "18-4-0",
      wins: 18, losses: 4, draws: 0,
      height: "6'4\"", weight: "265 lbs", reach: "80\"", stance: "Orthodox", age: 33,
      salary: 7000, projectedPoints: 58, avgFantasyPoints: 54,
      ownership: 15, knockoutPct: 39, submissionPct: 6, decisionPct: 55,
      strikeAccuracy: 47, strikeDefense: 57, takedownAccuracy: 52, takedownDefense: 63,
      significantStrikes: 3.8, takedownsPerFight: 3.8, ranking: 4,
    },
    {
      name: "Jamahal Hill",
      nickname: "Sweet Dreams",
      weightClass: "Light Heavyweight",
      record: "13-2-0",
      wins: 13, losses: 2, draws: 0,
      height: "6'4\"", weight: "205 lbs", reach: "84\"", stance: "Orthodox", age: 33,
      salary: 7500, projectedPoints: 63, avgFantasyPoints: 59,
      ownership: 20, knockoutPct: 69, submissionPct: 8, decisionPct: 23,
      strikeAccuracy: 49, strikeDefense: 55, takedownAccuracy: 30, takedownDefense: 70,
      significantStrikes: 4.4, takedownsPerFight: 0.6, ranking: 3,
    },
    {
      name: "Magomed Ankalaev",
      nickname: null,
      weightClass: "Light Heavyweight",
      record: "20-1-1",
      wins: 20, losses: 1, draws: 1,
      height: "6'3\"", weight: "205 lbs", reach: "76\"", stance: "Orthodox", age: 32,
      salary: 7500, projectedPoints: 61, avgFantasyPoints: 57,
      nationality: "Russia", countryFlag: "🇷🇺",
      ownership: 19, knockoutPct: 55, submissionPct: 20, decisionPct: 25,
      strikeAccuracy: 48, strikeDefense: 61, takedownAccuracy: 45, takedownDefense: 80,
      significantStrikes: 4.0, takedownsPerFight: 1.3, ranking: 4,
    },
    {
      name: "Gilbert Burns",
      nickname: "Durinho",
      weightClass: "Welterweight",
      record: "22-6-0",
      wins: 22, losses: 6, draws: 0,
      height: "5'10\"", weight: "170 lbs", reach: "71\"", stance: "Orthodox", age: 37,
      salary: 7000, projectedPoints: 57, avgFantasyPoints: 53,
      nationality: "Brazil", countryFlag: "🇧🇷",
      ownership: 14, knockoutPct: 36, submissionPct: 41, decisionPct: 23,
      strikeAccuracy: 46, strikeDefense: 56, takedownAccuracy: 56, takedownDefense: 73,
      significantStrikes: 3.9, takedownsPerFight: 1.7, ranking: 6,
    },
    {
      name: "Brian Ortega",
      nickname: "T-City",
      weightClass: "Featherweight",
      record: "16-3-0",
      wins: 16, losses: 3, draws: 0,
      height: "5'8\"", weight: "145 lbs", reach: "69\"", stance: "Orthodox", age: 33,
      salary: 7000, projectedPoints: 59, avgFantasyPoints: 55,
      ownership: 16, knockoutPct: 25, submissionPct: 69, decisionPct: 6,
      strikeAccuracy: 42, strikeDefense: 59, takedownAccuracy: 48, takedownDefense: 74,
      significantStrikes: 2.8, takedownsPerFight: 1.4, ranking: 5,
    },
    {
      name: "Yair Rodriguez",
      nickname: "El Pantera",
      weightClass: "Featherweight",
      record: "16-4-0",
      wins: 16, losses: 4, draws: 0,
      height: "5'11\"", weight: "145 lbs", reach: "72\"", stance: "Orthodox", age: 32,
      salary: 7000, projectedPoints: 60, avgFantasyPoints: 56,
      nationality: "Mexico", countryFlag: "🇲🇽",
      ownership: 17, knockoutPct: 63, submissionPct: 6, decisionPct: 31,
      strikeAccuracy: 45, strikeDefense: 57, takedownAccuracy: 31, takedownDefense: 75,
      significantStrikes: 4.4, takedownsPerFight: 0.5, ranking: 7,
    },
    {
      name: "Cory Sandhagen",
      nickname: "The Sandman",
      weightClass: "Bantamweight",
      record: "17-5-0",
      wins: 17, losses: 5, draws: 0,
      height: "5'11\"", weight: "135 lbs", reach: "70\"", stance: "Orthodox", age: 32,
      salary: 7500, projectedPoints: 62, avgFantasyPoints: 58,
      ownership: 21, knockoutPct: 59, submissionPct: 6, decisionPct: 35,
      strikeAccuracy: 50, strikeDefense: 58, takedownAccuracy: 41, takedownDefense: 77,
      significantStrikes: 4.7, takedownsPerFight: 0.9, ranking: 4,
    },
    {
      name: "Song Yadong",
      nickname: null,
      weightClass: "Bantamweight",
      record: "20-7-1",
      wins: 20, losses: 7, draws: 1,
      height: "5'7\"", weight: "135 lbs", reach: "68\"", stance: "Orthodox", age: 27,
      salary: 6500, projectedPoints: 56, avgFantasyPoints: 52,
      nationality: "China", countryFlag: "🇨🇳",
      ownership: 12, knockoutPct: 55, submissionPct: 10, decisionPct: 35,
      strikeAccuracy: 51, strikeDefense: 58, takedownAccuracy: 35, takedownDefense: 67,
      significantStrikes: 4.6, takedownsPerFight: 0.7, ranking: 6,
    },
    {
      name: "Brandon Moreno",
      nickname: "The Assassin Baby",
      weightClass: "Flyweight",
      record: "22-7-2",
      wins: 22, losses: 7, draws: 2,
      height: "5'7\"", weight: "125 lbs", reach: "68\"", stance: "Orthodox", age: 31,
      salary: 7500, projectedPoints: 61, avgFantasyPoints: 57,
      nationality: "Mexico", countryFlag: "🇲🇽",
      ownership: 20, knockoutPct: 36, submissionPct: 41, decisionPct: 23,
      strikeAccuracy: 44, strikeDefense: 53, takedownAccuracy: 50, takedownDefense: 66,
      significantStrikes: 3.8, takedownsPerFight: 2.0, ranking: 2,
    },
    {
      name: "Alexa Grasso",
      nickname: null,
      weightClass: "Women's Flyweight",
      record: "16-3-1",
      wins: 16, losses: 3, draws: 1,
      height: "5'4\"", weight: "125 lbs", reach: "65\"", stance: "Orthodox", age: 31,
      salary: 7500, projectedPoints: 62, avgFantasyPoints: 58,
      nationality: "Mexico", countryFlag: "🇲🇽",
      ownership: 22, knockoutPct: 31, submissionPct: 38, decisionPct: 31,
      strikeAccuracy: 48, strikeDefense: 55, takedownAccuracy: 42, takedownDefense: 68,
      significantStrikes: 3.6, takedownsPerFight: 1.3, ranking: 1,
    },
    {
      name: "Valentina Shevchenko",
      nickname: "Bullet",
      weightClass: "Women's Flyweight",
      record: "24-4-0",
      wins: 24, losses: 4, draws: 0,
      height: "5'4\"", weight: "125 lbs", reach: "67\"", stance: "Southpaw", age: 36,
      salary: 8000, projectedPoints: 65, avgFantasyPoints: 61,
      nationality: "Kyrgyzstan", countryFlag: "🇰🇬",
      ownership: 27, knockoutPct: 29, submissionPct: 38, decisionPct: 33,
      strikeAccuracy: 54, strikeDefense: 64, takedownAccuracy: 55, takedownDefense: 72,
      significantStrikes: 4.1, takedownsPerFight: 1.7, ranking: 2,
    },
    {
      name: "Stipe Miocic",
      nickname: null,
      weightClass: "Heavyweight",
      record: "20-4-0",
      wins: 20, losses: 4, draws: 0,
      height: "6'4\"", weight: "236 lbs", reach: "80\"", stance: "Orthodox", age: 42,
      salary: 7000, projectedPoints: 58, avgFantasyPoints: 54,
      ownership: 14, knockoutPct: 65, submissionPct: 5, decisionPct: 30,
      strikeAccuracy: 52, strikeDefense: 60, takedownAccuracy: 46, takedownDefense: 77,
      significantStrikes: 4.7, takedownsPerFight: 1.2, ranking: null,
    },
    {
      name: "Jan Blachowicz",
      nickname: "Prince of Cieszyn",
      weightClass: "Light Heavyweight",
      record: "30-11-0",
      wins: 30, losses: 11, draws: 0,
      height: "6'2\"", weight: "205 lbs", reach: "78\"", stance: "Orthodox", age: 41,
      salary: 6500, projectedPoints: 55, avgFantasyPoints: 51,
      nationality: "Poland", countryFlag: "🇵🇱",
      ownership: 11, knockoutPct: 60, submissionPct: 17, decisionPct: 23,
      strikeAccuracy: 44, strikeDefense: 58, takedownAccuracy: 30, takedownDefense: 71,
      significantStrikes: 3.5, takedownsPerFight: 0.7, ranking: 7,
    },
    {
      name: "Kamaru Usman",
      nickname: "The Nigerian Nightmare",
      weightClass: "Welterweight",
      record: "20-4-0",
      wins: 20, losses: 4, draws: 0,
      height: "6'0\"", weight: "170 lbs", reach: "76\"", stance: "Orthodox", age: 37,
      salary: 7500, projectedPoints: 62, avgFantasyPoints: 58,
      nationality: "Nigeria", countryFlag: "🇳🇬",
      ownership: 19, knockoutPct: 35, submissionPct: 15, decisionPct: 50,
      strikeAccuracy: 50, strikeDefense: 63, takedownAccuracy: 52, takedownDefense: 76,
      significantStrikes: 4.0, takedownsPerFight: 2.3, ranking: 5,
    },
    {
      name: "Beneil Dariush",
      nickname: "Benny",
      weightClass: "Lightweight",
      record: "22-5-0",
      wins: 22, losses: 5, draws: 0,
      height: "5'10\"", weight: "155 lbs", reach: "71\"", stance: "Orthodox", age: 35,
      salary: 7000, projectedPoints: 58, avgFantasyPoints: 54,
      ownership: 15, knockoutPct: 36, submissionPct: 45, decisionPct: 19,
      strikeAccuracy: 46, strikeDefense: 58, takedownAccuracy: 49, takedownDefense: 74,
      significantStrikes: 3.7, takedownsPerFight: 1.8, ranking: 6,
    },
    {
      name: "Rose Namajunas",
      nickname: "Thug",
      weightClass: "Women's Strawweight",
      record: "13-6-0",
      wins: 13, losses: 6, draws: 0,
      height: "5'5\"", weight: "115 lbs", reach: "65\"", stance: "Southpaw", age: 32,
      salary: 6500, projectedPoints: 55, avgFantasyPoints: 51,
      ownership: 13, knockoutPct: 31, submissionPct: 23, decisionPct: 46,
      strikeAccuracy: 49, strikeDefense: 60, takedownAccuracy: 38, takedownDefense: 68,
      significantStrikes: 3.9, takedownsPerFight: 0.8, ranking: 4,
    },
    {
      name: "Henry Cejudo",
      nickname: "Triple C",
      weightClass: "Bantamweight",
      record: "16-3-0",
      wins: 16, losses: 3, draws: 0,
      height: "5'4\"", weight: "135 lbs", reach: "64\"", stance: "Orthodox", age: 37,
      salary: 7000, projectedPoints: 59, avgFantasyPoints: 55,
      ownership: 16, knockoutPct: 38, submissionPct: 19, decisionPct: 43,
      strikeAccuracy: 44, strikeDefense: 57, takedownAccuracy: 60, takedownDefense: 78,
      significantStrikes: 3.4, takedownsPerFight: 2.7, ranking: 8,
    },
    {
      name: "Sean Brady",
      nickname: null,
      weightClass: "Welterweight",
      record: "17-1-0",
      wins: 17, losses: 1, draws: 0,
      height: "5'11\"", weight: "170 lbs", reach: "74\"", stance: "Orthodox", age: 31,
      salary: 6500, projectedPoints: 56, avgFantasyPoints: 52,
      ownership: 13, knockoutPct: 24, submissionPct: 47, decisionPct: 29,
      strikeAccuracy: 44, strikeDefense: 61, takedownAccuracy: 58, takedownDefense: 78,
      significantStrikes: 3.2, takedownsPerFight: 2.9, ranking: 8,
    },
    {
      name: "Marlon Vera",
      nickname: "Chito",
      weightClass: "Bantamweight",
      record: "22-9-1",
      wins: 22, losses: 9, draws: 1,
      height: "5'7\"", weight: "135 lbs", reach: "66\"", stance: "Orthodox", age: 31,
      salary: 6500, projectedPoints: 57, avgFantasyPoints: 53,
      nationality: "Ecuador", countryFlag: "🇪🇨",
      ownership: 14, knockoutPct: 41, submissionPct: 18, decisionPct: 41,
      strikeAccuracy: 46, strikeDefense: 55, takedownAccuracy: 36, takedownDefense: 65,
      significantStrikes: 4.2, takedownsPerFight: 0.9, ranking: 5,
    },
    {
      name: "Brandon Royval",
      nickname: "Raw Dawg",
      weightClass: "Flyweight",
      record: "16-8-0",
      wins: 16, losses: 8, draws: 0,
      height: "5'6\"", weight: "125 lbs", reach: "69\"", stance: "Orthodox", age: 31,
      salary: 6000, projectedPoints: 52, avgFantasyPoints: 48,
      ownership: 10, knockoutPct: 31, submissionPct: 50, decisionPct: 19,
      strikeAccuracy: 43, strikeDefense: 51, takedownAccuracy: 47, takedownDefense: 62,
      significantStrikes: 3.6, takedownsPerFight: 2.2, ranking: 5,
    },
    {
      name: "Tai Tuivasa",
      nickname: "Bam Bam",
      weightClass: "Heavyweight",
      record: "15-7-0",
      wins: 15, losses: 7, draws: 0,
      height: "6'2\"", weight: "264 lbs", reach: "76\"", stance: "Orthodox", age: 31,
      salary: 6500, projectedPoints: 60, avgFantasyPoints: 56,
      nationality: "Australia", countryFlag: "🇦🇺",
      ownership: 17, knockoutPct: 80, submissionPct: 7, decisionPct: 13,
      strikeAccuracy: 52, strikeDefense: 50, takedownAccuracy: 18, takedownDefense: 59,
      significantStrikes: 5.3, takedownsPerFight: 0.3, ranking: null,
    },
    {
      name: "Josh Emmett",
      nickname: "The Honey Badger",
      weightClass: "Featherweight",
      record: "18-4-0",
      wins: 18, losses: 4, draws: 0,
      height: "5'6\"", weight: "145 lbs", reach: "66\"", stance: "Orthodox", age: 38,
      salary: 6500, projectedPoints: 56, avgFantasyPoints: 52,
      ownership: 12, knockoutPct: 67, submissionPct: 6, decisionPct: 27,
      strikeAccuracy: 47, strikeDefense: 56, takedownAccuracy: 32, takedownDefense: 71,
      significantStrikes: 4.0, takedownsPerFight: 0.7, ranking: 9,
    },
    {
      name: "Matt Schnell",
      nickname: "Danger",
      weightClass: "Flyweight",
      record: "17-8-0",
      wins: 17, losses: 8, draws: 0,
      height: "5'4\"", weight: "125 lbs", reach: "65\"", stance: "Southpaw", age: 34,
      salary: 5500, projectedPoints: 48, avgFantasyPoints: 44,
      ownership: 8, knockoutPct: 35, submissionPct: 35, decisionPct: 30,
      strikeAccuracy: 42, strikeDefense: 52, takedownAccuracy: 44, takedownDefense: 60,
      significantStrikes: 3.1, takedownsPerFight: 1.5, ranking: null,
    },
    {
      name: "Amanda Lemos",
      nickname: "Baianinha",
      weightClass: "Women's Strawweight",
      record: "14-4-1",
      wins: 14, losses: 4, draws: 1,
      height: "5'4\"", weight: "115 lbs", reach: "64\"", stance: "Orthodox", age: 36,
      salary: 6000, projectedPoints: 53, avgFantasyPoints: 49,
      nationality: "Brazil", countryFlag: "🇧🇷",
      ownership: 11, knockoutPct: 43, submissionPct: 36, decisionPct: 21,
      strikeAccuracy: 47, strikeDefense: 53, takedownAccuracy: 40, takedownDefense: 62,
      significantStrikes: 3.8, takedownsPerFight: 1.0, ranking: 6,
    },
    {
      name: "Yan Xiaonan",
      nickname: "Fury",
      weightClass: "Women's Strawweight",
      record: "18-4-0",
      wins: 18, losses: 4, draws: 0,
      height: "5'6\"", weight: "115 lbs", reach: "66\"", stance: "Orthodox", age: 33,
      salary: 6500, projectedPoints: 57, avgFantasyPoints: 53,
      nationality: "China", countryFlag: "🇨🇳",
      ownership: 14, knockoutPct: 28, submissionPct: 11, decisionPct: 61,
      strikeAccuracy: 50, strikeDefense: 61, takedownAccuracy: 42, takedownDefense: 70,
      significantStrikes: 4.4, takedownsPerFight: 0.9, ranking: 3,
    },
    {
      name: "Maycee Barber",
      nickname: "The Future",
      weightClass: "Women's Flyweight",
      record: "15-3-0",
      wins: 15, losses: 3, draws: 0,
      height: "5'7\"", weight: "125 lbs", reach: "68\"", stance: "Orthodox", age: 26,
      salary: 5500, projectedPoints: 50, avgFantasyPoints: 46,
      ownership: 9, knockoutPct: 40, submissionPct: 7, decisionPct: 53,
      strikeAccuracy: 44, strikeDefense: 52, takedownAccuracy: 35, takedownDefense: 61,
      significantStrikes: 3.5, takedownsPerFight: 0.8, ranking: 4,
    },
    {
      name: "Alexander Volkov",
      nickname: "Drago",
      weightClass: "Heavyweight",
      record: "38-10-0",
      wins: 38, losses: 10, draws: 0,
      height: "6'7\"", weight: "247 lbs", reach: "80\"", stance: "Orthodox", age: 36,
      salary: 6000, projectedPoints: 55, avgFantasyPoints: 51,
      nationality: "Russia", countryFlag: "🇷🇺",
      ownership: 11, knockoutPct: 47, submissionPct: 8, decisionPct: 45,
      strikeAccuracy: 46, strikeDefense: 56, takedownAccuracy: 27, takedownDefense: 71,
      significantStrikes: 3.8, takedownsPerFight: 0.5, ranking: 6,
    },
    {
      name: "Serghei Spivac",
      nickname: "Polar Bear",
      weightClass: "Heavyweight",
      record: "16-3-0",
      wins: 16, losses: 3, draws: 0,
      height: "6'3\"", weight: "246 lbs", reach: "76\"", stance: "Orthodox", age: 29,
      salary: 6500, projectedPoints: 58, avgFantasyPoints: 54,
      nationality: "Moldova", countryFlag: "🇲🇩",
      ownership: 14, knockoutPct: 56, submissionPct: 31, decisionPct: 13,
      strikeAccuracy: 49, strikeDefense: 58, takedownAccuracy: 42, takedownDefense: 68,
      significantStrikes: 3.9, takedownsPerFight: 1.4, ranking: 5,
    },
    {
      name: "David Dvorak",
      nickname: null,
      weightClass: "Flyweight",
      record: "22-5-0",
      wins: 22, losses: 5, draws: 0,
      height: "5'6\"", weight: "125 lbs", reach: "67\"", stance: "Orthodox", age: 30,
      salary: 5500, projectedPoints: 47, avgFantasyPoints: 43,
      nationality: "Czech Republic", countryFlag: "🇨🇿",
      ownership: 8, knockoutPct: 27, submissionPct: 36, decisionPct: 37,
      strikeAccuracy: 44, strikeDefense: 54, takedownAccuracy: 49, takedownDefense: 65,
      significantStrikes: 3.3, takedownsPerFight: 1.8, ranking: null,
    },
    {
      name: "Carla Esparza",
      nickname: "Cookie Monster",
      weightClass: "Women's Strawweight",
      record: "20-8-0",
      wins: 20, losses: 8, draws: 0,
      height: "5'1\"", weight: "115 lbs", reach: "62\"", stance: "Orthodox", age: 37,
      salary: 5500, projectedPoints: 48, avgFantasyPoints: 44,
      ownership: 9, knockoutPct: 5, submissionPct: 45, decisionPct: 50,
      strikeAccuracy: 40, strikeDefense: 58, takedownAccuracy: 62, takedownDefense: 74,
      significantStrikes: 2.8, takedownsPerFight: 3.4, ranking: 8,
    },
  ];

  console.log(`Creating ${fightersData.length} fighters...`);
  for (const fighter of fightersData) {
    await prisma.fighter.upsert({
      where: { id: fighter.name.toLowerCase().replace(/[^a-z0-9]/g, "-") },
      update: fighter,
      create: {
        id: fighter.name.toLowerCase().replace(/[^a-z0-9]/g, "-"),
        ...fighter,
        imageUrl: `https://via.placeholder.com/300x300/0f1520/39FF14?text=${encodeURIComponent(
          fighter.name.split(" ").map((n) => n[0]).join("")
        )}`,
      },
    });
  }

  // Create events
  const ufc315 = await prisma.event.upsert({
    where: { id: "ufc-315" },
    update: {},
    create: {
      id: "ufc-315",
      name: "UFC 315",
      shortName: "UFC 315",
      venue: "T-Mobile Arena",
      city: "Las Vegas",
      country: "USA",
      date: new Date("2025-05-31T22:00:00Z"),
      status: EventStatus.UPCOMING,
      broadcasters: ["ESPN+", "PPV"],
      mainCardTime: "10:00 PM ET",
      prelimTime: "6:00 PM ET",
      description: "Championship night featuring the best fighters in the world.",
    },
  });

  const ufc316 = await prisma.event.upsert({
    where: { id: "ufc-316" },
    update: {},
    create: {
      id: "ufc-316",
      name: "UFC 316",
      shortName: "UFC 316",
      venue: "United Center",
      city: "Chicago",
      country: "USA",
      date: new Date("2025-06-28T22:00:00Z"),
      status: EventStatus.UPCOMING,
      broadcasters: ["ESPN+", "PPV"],
      mainCardTime: "10:00 PM ET",
      prelimTime: "6:00 PM ET",
      description: "Big fights coming to Chicago.",
    },
  });

  // Create achievements
  const achievements = [
    { name: "First Blood", description: "Enter your first contest", icon: "🩸", xpReward: 50, rarity: "common", category: "contests" },
    { name: "Sharp Shooter", description: "Score 100+ fantasy points in a contest", icon: "🎯", xpReward: 150, rarity: "rare", category: "performance" },
    { name: "Champion", description: "Win your first contest", icon: "🏆", xpReward: 300, rarity: "rare", category: "contests" },
    { name: "Grind", description: "Maintain a 7-day login streak", icon: "🔥", xpReward: 100, rarity: "common", category: "engagement" },
    { name: "Scholar", description: "View 20 fighter profiles", icon: "📚", xpReward: 75, rarity: "common", category: "exploration" },
    { name: "High Roller", description: "Enter a $50+ contest", icon: "💰", xpReward: 200, rarity: "epic", category: "contests" },
    { name: "Perfect Pick", description: "Pick a first-round finish correctly", icon: "⚡", xpReward: 250, rarity: "epic", category: "performance" },
    { name: "Legend", description: "Reach level 6", icon: "⭐", xpReward: 500, rarity: "legendary", category: "progression" },
    { name: "Social Butterfly", description: "Add 5 friends", icon: "🤝", xpReward: 100, rarity: "common", category: "social" },
    { name: "Millionaire", description: "Win $1,000+ in total", icon: "💎", xpReward: 1000, rarity: "legendary", category: "contests" },
  ];

  for (const ach of achievements) {
    await prisma.achievement.create({ data: ach }).catch(() => {});
  }

  // Create public contests for UFC 315
  await prisma.contest.create({
    data: {
      id: "ufc315-main",
      eventId: ufc315.id,
      creatorId: admin.id,
      name: "UFC 315 Main Event Showdown",
      type: ContestType.PUBLIC,
      status: ContestStatus.OPEN,
      entryFee: 0,
      prizePool: 1000,
      maxEntries: 1000,
      currentEntries: 247,
      salaryCap: 50000,
      rosterSize: 6,
      isGuaranteed: true,
    },
  }).catch(() => {});

  await prisma.contest.create({
    data: {
      id: "ufc315-hof",
      eventId: ufc315.id,
      creatorId: admin.id,
      name: "UFC 315 Hall of Fame — $10K GTD",
      type: ContestType.PUBLIC,
      status: ContestStatus.OPEN,
      entryFee: 10,
      prizePool: 10000,
      maxEntries: 500,
      currentEntries: 183,
      salaryCap: 50000,
      rosterSize: 6,
      isGuaranteed: true,
    },
  }).catch(() => {});

  await prisma.contest.create({
    data: {
      id: "ufc315-headtohead",
      eventId: ufc315.id,
      creatorId: admin.id,
      name: "Head-to-Head Challenge",
      type: ContestType.HEAD_TO_HEAD,
      status: ContestStatus.OPEN,
      entryFee: 5,
      prizePool: 9,
      maxEntries: 2,
      currentEntries: 0,
      salaryCap: 50000,
      rosterSize: 6,
      isGuaranteed: false,
    },
  }).catch(() => {});

  console.log("✅ Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
